/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElyButton: typeof import('./src/components/ElyButton.vue')['default']
    ElyFooter: typeof import('./src/components/ElyFooter.vue')['default']
    ElyLayout: typeof import('./src/components/ElyLayout.vue')['default']
    ElyNavbar: typeof import('./src/components/ElyNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
