/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElyAlert: typeof import('./src/components/ElyAlert.vue')['default']
    ElyButton: typeof import('./src/components/ElyButton.vue')['default']
    ElyButtonEdit: typeof import('./src/components/ElyButtonEdit.vue')['default']
    ElyDocLayout: typeof import('./src/components/ElyDocLayout.vue')['default']
    ElyFooter: typeof import('./src/components/ElyFooter.vue')['default']
    ElyLayout: typeof import('./src/components/ElyLayout.vue')['default']
    ElyLoader: typeof import('./src/components/ElyLoader.vue')['default']
    ElyNavbar: typeof import('./src/components/ElyNavbar.vue')['default']
    ElySidebar: typeof import('./src/components/ElySidebar.vue')['default']
    ElyTerminal: typeof import('./src/components/ElyTerminal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
