/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElyAlert: typeof import('./src/components/ElyAlert.vue')['default']
    ElyAvatar: typeof import('./src/components/ElyAvatar.vue')['default']
    ElyBadge: typeof import('./src/components/ElyBadge.vue')['default']
    ElyButton: typeof import('./src/components/ElyButton.vue')['default']
    ElyCheckbox: typeof import('./src/components/ElyCheckbox.vue')['default']
    ElyInput: typeof import('./src/components/ElyInput.vue')['default']
    ElyLoader: typeof import('./src/components/ElyLoader.vue')['default']
    ElyModal: typeof import('./src/components/ElyModal.vue')['default']
    ElyProgress: typeof import('./src/components/ElyProgress.vue')['default']
    ElyProgressCircular: typeof import('./src/components/ElyProgressCircular.vue')['default']
    ElyRadio: typeof import('./src/components/ElyRadio.vue')['default']
    ElySwitch: typeof import('./src/components/ElySwitch.vue')['default']
    ElyTerminal: typeof import('./src/components/ElyTerminal.vue')['default']
    ElyTextarea: typeof import('./src/components/ElyTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
