/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElyAlert: typeof import('./src/components/ElyAlert.vue')['default']
    ElyButton: typeof import('./src/components/ElyButton.vue')['default']
    ElyLoader: typeof import('./src/components/ElyLoader.vue')['default']
    ElyTerminal: typeof import('./src/components/ElyTerminal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
