name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js and pnpm
      uses: actions/setup-node@v3
      with:
        node-version: 14
      run: |
        npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm run test

    - name: Build library
      run: pnpm run build